export class Size {
  static readonly PAGE_PADDING = 16
  static readonly CARD_RADIUS = 12
  static readonly BUTTON_RADIUS = 8
  static readonly TAB_HEIGHT = 56
  static readonly NAV_BAR_HEIGHT = 44
  static readonly ICON_SM = 16
  static readonly ICON_MD = 24
  static readonly ICON_LG = 32
  static readonly FONT_XS = 10
  static readonly FONT_SM = 12
  static readonly FONT_MD = 14
  static readonly FONT_LG = 16
  static readonly FONT_XL = 18
  static readonly FONT_XXL = 20
  static readonly FONT_TITLE = 24
}
